apiVersion: v1
kind: Pod
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: busybox
      command: ['sh','-c','echo Hello Mr.Mangam && sleep 3600']
