apiVersion: v1
kind: Pod
metadata:
  name: http-app
  labels:
    app: hello
spec:
  containers:
    - name: http-app
      image: sunilmangam/mangam-httpd
      ports:
        - containerPort: 80
          hostPort: 9020
